output "resource_group_name" {
  value = azurerm_resource_group.rg.name
}

output "acr_login_server" {
  value = azurerm_container_registry.acr.login_server
}

output "frontend_vm_public_ip" {
  value = azurerm_public_ip.frontend_pip.ip_address
}

output "backend_vm_public_ip" {
  value = azurerm_public_ip.backend_pip.ip_address
}

output "mysql_server_fqdn" {
  description = "The fully qualified domain name of the Azure MySQL Flexible Server."
  value       = azurerm_mysql_flexible_server.mysql.fqdn
}

output "jobtracker_private_key" {
  description = "The private SSH key generated by Terraform."
  value       = tls_private_key.jobtracker.private_key_pem
  sensitive   = true
}
