name: Build and Push Frontend

on:
  push:
    branches: [ main ]   # Runs when code is pushed to main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Frontend Docker Image
        run: |
          docker build -t jobtrack-frontend:latest -f frontend/Dockerfile frontend/

      - name: Tag Frontend Docker Image
        run: |
          docker tag jobtrack-frontend:latest ${{ secrets.ACR_LOGIN_SERVER }}/jobtrack-frontend:latest

      - name: Push Frontend Image to ACR
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/jobtrack-frontend:latest

      - name: Verify Image Exists in ACR
        run: |
          az acr repository show-tags \
          --name $(echo "${{ secrets.ACR_LOGIN_SERVER }}" | cut -d'.' -f1) \
          --repository jobtrack-frontend \
          --username ${{ secrets.ACR_USERNAME }} \
          --password ${{ secrets.ACR_PASSWORD }} \
          --output table

      - name: Trigger Backend Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}  # GitHub PAT for triggering the backend repo
          repository: Infinity-5tack/Job-Tracker-Application-Backend  # Replace with actual backend repo
          event-type: frontend_image_pushed
          
